### PR TITLE
added pen pal analogy

### PR DESCRIPTION
**Pull request by gnubufferoverflows**
Perhaps it isn't the most zoomer explanation, but I think it is pretty good.

### CODE REVIEW

**Review by detjensrobert — CHANGES_REQUESTED** [review]
The tone of this seems a little too demeaning for the goal of this site. `Of course not`, `Obviously` etc make this section feel like its talking down to the reader, which is explicitly what this site is trying to avoid vs. dontasktoask and etc

**Comment by gnubufferoverflows** [comment]
Here I'll edit it a bit and see what I can do @detjensrobert.

**Comment by gnubufferoverflows** [comment]
I might take another look at it later with a fresh set of eyes, but hopefully that is more friendly sounding.

**Comment by radian628** [comment]
I like the changes you made--- looks good to me!

**Pull request merged**
